"use strict";

const {QUESTION_PROMPT,EVALUATOR_PROMPT}=require("./prompts");
const {cleanText,compactJd,validateQuestions,validateEvaluation}=require("./validators");

const MODEL="deepseek-flash",API_URL="https://api.deepseek.com/chat/completions",TIMEOUT_MS=25000,MAX_BODY_BYTES=26000;
const buckets=new Map();
class SafeError extends Error{constructor(code,message,status=500){super(message);this.code=code;this.status=status}}
const headers={"Content-Type":"application/json; charset=utf-8","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type","Access-Control-Allow-Methods":"POST, OPTIONS","Cache-Control":"no-store"};
const response=(status,body)=>({statusCode:status,headers,body:JSON.stringify(body)});
function clientId(event){return cleanText(event?.headers?.["x-forwarded-for"]||event?.headers?.["X-Forwarded-For"]||event?.requestContext?.sourceIp||"anonymous",128).split(",")[0]}
function rateLimit(id){const now=Date.now(),key=id||"anonymous",item=buckets.get(key)||{start:now,count:0};if(now-item.start>60000){item.start=now;item.count=0}item.count++;buckets.set(key,item);if(item.count>10)throw new SafeError("RATE_LIMITED","请求过于频繁，请稍后再试。",429);if(buckets.size>1000)for(const [k,v] of buckets)if(now-v.start>120000)buckets.delete(k)}
function parseEvent(event){if(event?.httpMethod==="OPTIONS")return null;if(event?.httpMethod&&event.httpMethod!=="POST")throw new SafeError("METHOD_NOT_ALLOWED","仅支持 POST 请求。",405);let raw=event?.body??event;if(typeof raw==="string"){if(Buffer.byteLength(raw,"utf8")>MAX_BODY_BYTES)throw new SafeError("INPUT_TOO_LONG","输入内容过长，请缩短后重试。",413);try{raw=JSON.parse(event?.isBase64Encoded?Buffer.from(raw,"base64").toString("utf8"):raw)}catch{throw new SafeError("INVALID_REQUEST","请求格式无效。",400)}}if(!raw||typeof raw!=="object")throw new SafeError("INVALID_REQUEST","请求格式无效。",400);return raw}
function commonInput(body){const company=cleanText(body.company,120),position=cleanText(body.position,120),jd=compactJd(body.jd);if(!position||!jd)throw new SafeError("INVALID_REQUEST","请填写岗位和 Job Description。",400);return{company,position,jd}}
function parseJson(content){if(typeof content!=="string"||!content.trim())throw new SafeError("INVALID_RESPONSE","AI 返回内容为空，请重试。",502);try{return JSON.parse(content)}catch{throw new SafeError("INVALID_RESPONSE","AI 返回格式不完整，请重试。",502)}}
async function callDeepSeek(system,user,maxTokens){const key=process.env.DEEPSEEK_API_KEY;if(!key)throw new SafeError("NOT_CONFIGURED","模拟面试服务尚未完成配置。",503);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),TIMEOUT_MS);let res;try{res=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${key}`},body:JSON.stringify({model:MODEL,messages:[{role:"system",content:system},{role:"user",content:user}],response_format:{type:"json_object"},thinking:{type:"disabled"},temperature:.25,max_tokens:maxTokens,stream:false}),signal:controller.signal})}catch(error){if(error?.name==="AbortError")throw new SafeError("TIMEOUT","AI 请求超时，请稍后重试。",504);throw new SafeError("NETWORK_ERROR","AI 服务网络连接失败，请稍后重试。",502)}finally{clearTimeout(timer)}if(!res.ok){if(res.status===401)throw new SafeError("AUTH_ERROR","AI 服务配置无效，请联系维护者。",503);if(res.status===402)throw new SafeError("INSUFFICIENT_BALANCE","AI 服务余额不足，请联系维护者。",503);if(res.status===429)throw new SafeError("RATE_LIMITED","AI 服务请求繁忙，请稍后重试。",429);if(res.status===400||res.status===422)throw new SafeError("API_ERROR","AI 请求参数暂时无法处理，请重试。",502);throw new SafeError("API_ERROR","AI 服务暂时不可用，请稍后重试。",502)}let payload;try{payload=await res.json()}catch{throw new SafeError("INVALID_RESPONSE","AI 返回格式无效，请重试。",502)}const choice=payload?.choices?.[0];if(choice?.finish_reason==="length")throw new SafeError("INVALID_RESPONSE","AI 返回被截断，请重试。",502);return{data:parseJson(choice?.message?.content),usage:payload?.usage||null}}
function questionPayload(body){const input=commonInput(body);return JSON.stringify({company:input.company||"Not provided",position:input.position,job_description:input.jd})}
function evaluationPayload(body){const input=commonInput(body),q=body.question||{},answer=cleanText(body.answer,6000),previousAnswer=cleanText(body.previous_answer,6000),previous=body.previous_feedback;if(!cleanText(q.question,500)||!answer)throw new SafeError("INVALID_REQUEST","问题或回答为空。",400);return{isRetry:Boolean(previousAnswer&&previous),text:JSON.stringify({company:input.company||"Not provided",position:input.position,job_description:input.jd,question:cleanText(q.question,500),question_competency:cleanText(q.competency,80),user_answer:answer,previous_attempt:previousAnswer?{answer:previousAnswer,diagnosis:{total_score:previous?.total_score,biggest_weakness:cleanText(previous?.biggest_weakness,700),retry_focus:Array.isArray(previous?.retry_focus)?previous.retry_focus.slice(0,2):[]}}:null})}}
async function handle(body){if(body.action==="generate"){const result=await callDeepSeek(QUESTION_PROMPT,questionPayload(body),1600);return{data:validateQuestions(result.data),usage:result.usage}}if(body.action==="evaluate"){const payload=evaluationPayload(body),result=await callDeepSeek(EVALUATOR_PROMPT,payload.text,2600);return{data:validateEvaluation(result.data,payload.isRetry),usage:result.usage}}throw new SafeError("INVALID_REQUEST","不支持的操作。",400)}
async function main(event){try{const body=parseEvent(event);if(body===null)return response(204,{});rateLimit(clientId(event));const result=await handle(body);return response(200,{ok:true,data:result.data,meta:{model:MODEL,usage:result.usage}})}catch(error){const safe=error instanceof SafeError||error?.code==="INVALID_RESPONSE";return response(safe?(error.status||502):500,{ok:false,code:safe?error.code:"SERVER_ERROR",message:safe?error.message:"服务暂时不可用，请稍后重试。"})}}

exports.main=main;
exports._test={MODEL,API_URL,TIMEOUT_MS,MAX_BODY_BYTES,parseEvent,commonInput,questionPayload,evaluationPayload,parseJson,handle,rateLimit,SafeError};
