"use strict";

const scoreKeys=["relevance_score","structure_score","evidence_score","action_result_score","clarity_score","english_score"];
const isText=v=>typeof v==="string"&&v.trim().length>0;
const cleanText=(value,max)=>String(value??"").replace(/\0/g,"").replace(/\s+/g," ").trim().slice(0,max);
const sanitizePlaceholders=value=>String(value??"").replace(/\[([^\]]+)\]/g,(_,content)=>`[${content.split(/,|;|:|\bsuch as\b|\be\.g\.?\b/i)[0].trim()}]`);
const compactJd=value=>{const jd=cleanText(value,12000);return jd.length<=10000?jd:`${jd.slice(0,8000)}\n[Middle of long JD omitted]\n${jd.slice(-2000)}`};
function validateQuestions(value){if(!value||!Array.isArray(value.questions)||value.questions.length!==5)throw invalid();const seen=new Set();value.questions=value.questions.map((q,i)=>{if(!q||!isText(q.question)||!isText(q.chinese)||!isText(q.competency)||!isText(q.jd_connection))throw invalid();const question=cleanText(q.question,500);if(seen.has(question.toLowerCase()))throw invalid();seen.add(question.toLowerCase());return{id:`q${i+1}`,question,chinese:cleanText(q.chinese,300),competency:cleanText(q.competency,80),jd_connection:cleanText(q.jd_connection,300)}});return value}
function validateEvaluation(value,isRetry){if(!value||typeof value!=="object")throw invalid();scoreKeys.forEach(k=>{if(!Number.isInteger(value[k])||value[k]<0||value[k]>5)throw invalid()});value.total_score=scoreKeys.reduce((s,k)=>s+value[k],0);if(!isText(value.overall_diagnosis)||!isText(value.biggest_weakness)||!isText(value.suggested_answer))throw invalid();for(const key of ["strengths","improvement_advice","better_structure","retry_focus","improved","still_missing"]){if(!Array.isArray(value[key]))throw invalid();value[key]=value[key].filter(isText).map(x=>cleanText(x,700))}if(value.strengths.length<1||value.strengths.length>2||value.improvement_advice.length<1||value.retry_focus.length<1||value.retry_focus.length>2)throw invalid();if(isRetry&&(!value.improved.length||!value.still_missing.length))throw invalid();if(!Array.isArray(value.language_fixes))throw invalid();value.language_fixes=value.language_fixes.slice(0,5).map(x=>({original:cleanText(x?.original,300),improved:cleanText(x?.improved,300),reason:cleanText(x?.reason,300)})).filter(x=>x.original&&x.improved&&x.reason&&x.original.toLowerCase()!==x.improved.toLowerCase());value.overall_diagnosis=cleanText(value.overall_diagnosis,500);value.biggest_weakness=cleanText(value.biggest_weakness,700);value.suggested_answer=cleanText(sanitizePlaceholders(value.suggested_answer),3000);value.suggested_answer_rationale=cleanText(value.suggested_answer_rationale,700);return value}
function invalid(){const error=new Error("Invalid AI response");error.code="INVALID_RESPONSE";return error}
module.exports={scoreKeys,cleanText,sanitizePlaceholders,compactJd,validateQuestions,validateEvaluation,invalid};
