"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const fn=require("../cloudfunctions/eitMockInterview/index.js"),validators=require("../cloudfunctions/eitMockInterview/validators.js");

const base={company:"",position:"Product Operations Intern",jd:"Support user research, analyze campaign data, coordinate content execution, and communicate findings clearly."};
test("evaluator forbids examples or sample values that invent candidate facts",()=>{const prompt=require("../cloudfunctions/eitMockInterview/prompts.js").EVALUATOR_PROMPT;assert.match(prompt,/Every factual detail must be directly traceable/);assert.match(prompt,/placeholder must not contain a sample value/)});
test("evaluator requests Chinese teaching feedback without changing the scoring scale",()=>{const prompt=require("../cloudfunctions/eitMockInterview/prompts.js").EVALUATOR_PROMPT;assert.match(prompt,/primarily in concise, natural Simplified Chinese/);assert.match(prompt,/suggested_answer: simple English, strong answer/);assert.match(prompt,/Keep the six scoring standards and 0–5 scale exactly/);assert.match(prompt,/Point：中文逻辑说明/)});
test("sample text is removed from missing-fact placeholders",()=>{assert.equal(validators.sanitizePlaceholders("It led to [add the real result, such as a 20% increase]."),"It led to [add the real result].")});
test("language fixes with no actual change are removed",()=>{const value={relevance_score:4,structure_score:3,evidence_score:2,action_result_score:3,clarity_score:4,english_score:5,overall_diagnosis:"Relevant but needs evidence.",strengths:["The role connection is explicit."],biggest_weakness:"No concrete example.",improvement_advice:["Add one real example."],language_fixes:[{original:"This is clear.",improved:"This is clear.",reason:"No change needed."}],better_structure:["Point","Evidence","Action","Result","Tie-back"],suggested_answer:"I would add [your real example].",retry_focus:["Add evidence"],improved:[],still_missing:[]};assert.equal(validators.validateEvaluation(value,false).language_fixes.length,0)});
test("long JD is deterministically compacted",()=>{const text="A".repeat(13000);const value=validators.compactJd(text);assert.ok(value.length<=10032);assert.match(value,/Middle of long JD omitted/)});
test("company may be empty while position and JD are required",()=>{assert.equal(fn._test.commonInput(base).company,"");assert.throws(()=>fn._test.commonInput({...base,position:""}),/岗位/)});
test("question validator requires five unique complete questions",()=>{const questions=Array.from({length:5},(_,i)=>({question:`Question ${i+1}?`,chinese:`问题 ${i+1}`,competency:"execution",jd_connection:"JD requires execution"}));assert.equal(validators.validateQuestions({questions}).questions.length,5);assert.throws(()=>validators.validateQuestions({questions:questions.slice(0,4)}))});
test("evaluation total is calculated from six scores",()=>{const value={relevance_score:4,structure_score:3,evidence_score:2,action_result_score:3,clarity_score:4,english_score:5,total_score:0,overall_diagnosis:"Relevant but needs evidence.",strengths:["The role connection is explicit."],biggest_weakness:"No concrete example.",improvement_advice:["Add one real example."],language_fixes:[],better_structure:["Point","Evidence","Action","Result","Tie-back"],suggested_answer:"I would add [your real example].",retry_focus:["Add evidence"],improved:[],still_missing:[]};assert.equal(validators.validateEvaluation(value,false).total_score,21)});
test("missing key returns a safe configuration error",async()=>{const old=process.env.DEEPSEEK_API_KEY;delete process.env.DEEPSEEK_API_KEY;const result=await fn.main({httpMethod:"POST",headers:{"x-forwarded-for":"test-config"},body:JSON.stringify({action:"generate",...base})});const body=JSON.parse(result.body);assert.equal(result.statusCode,503);assert.equal(body.code,"NOT_CONFIGURED");if(old)process.env.DEEPSEEK_API_KEY=old});
test("DeepSeek errors never expose response bodies or credentials",async()=>{const oldFetch=global.fetch,oldKey=process.env.DEEPSEEK_API_KEY;process.env.DEEPSEEK_API_KEY="test-placeholder-not-a-real-key";global.fetch=async()=>({ok:false,status:402,json:async()=>({error:{message:"private provider detail"}})});const result=await fn.main({httpMethod:"POST",headers:{"x-forwarded-for":"test-balance"},body:JSON.stringify({action:"generate",...base})});const text=result.body;assert.equal(result.statusCode,503);assert.match(text,/INSUFFICIENT_BALANCE/);assert.doesNotMatch(text,/private provider detail|test-placeholder/);global.fetch=oldFetch;if(oldKey)process.env.DEEPSEEK_API_KEY=oldKey;else delete process.env.DEEPSEEK_API_KEY});
test("successful generation uses current low-latency JSON configuration",async()=>{const oldFetch=global.fetch,oldKey=process.env.DEEPSEEK_API_KEY;process.env.DEEPSEEK_API_KEY="test-placeholder-not-a-real-key";let sent;const questions=Array.from({length:5},(_,i)=>({id:`q${i+1}`,question:`JD-related question ${i+1}?`,chinese:`岗位问题 ${i+1}`,competency:"execution",jd_connection:"The JD requires execution."}));global.fetch=async(_url,options)=>{sent=JSON.parse(options.body);return{ok:true,status:200,json:async()=>({choices:[{finish_reason:"stop",message:{content:JSON.stringify({questions})}}],usage:{prompt_tokens:100,completion_tokens:200,total_tokens:300}})}};const result=await fn.main({httpMethod:"POST",headers:{"x-forwarded-for":"test-generate"},body:JSON.stringify({action:"generate",...base})});const body=JSON.parse(result.body);assert.equal(result.statusCode,200);assert.equal(body.data.questions.length,5);assert.equal(sent.model,"deepseek-flash");assert.deepEqual(sent.response_format,{type:"json_object"});assert.deepEqual(sent.thinking,{type:"disabled"});assert.equal(sent.max_tokens,1600);global.fetch=oldFetch;if(oldKey)process.env.DEEPSEEK_API_KEY=oldKey;else delete process.env.DEEPSEEK_API_KEY});
test("retry evaluation requires and returns comparison fields",async()=>{const oldFetch=global.fetch,oldKey=process.env.DEEPSEEK_API_KEY;process.env.DEEPSEEK_API_KEY="test-placeholder-not-a-real-key";const evaluation={relevance_score:4,structure_score:4,evidence_score:3,action_result_score:3,clarity_score:4,english_score:4,total_score:0,overall_diagnosis:"The answer is clearer and more specific.",strengths:["The personal action is now explicit."],biggest_weakness:"The result remains general.",improvement_advice:["Add a real result."],language_fixes:[],better_structure:["Point","Evidence","Action","Result","Tie-back"],suggested_answer:"I took [your real action], which led to [your real result].",retry_focus:["Add the real result"],improved:["The personal action is clearer than before."],still_missing:["A real outcome is still missing."]};global.fetch=async()=>({ok:true,status:200,json:async()=>({choices:[{finish_reason:"stop",message:{content:JSON.stringify(evaluation)}}],usage:{prompt_tokens:200,completion_tokens:300,total_tokens:500}})});const result=await fn.main({httpMethod:"POST",headers:{"x-forwarded-for":"test-retry"},body:JSON.stringify({action:"evaluate",...base,question:{question:"Tell me about a project.",competency:"execution"},answer:"I organized the work and delivered the draft.",previous_answer:"We did the project.",previous_feedback:{total_score:12,biggest_weakness:"No personal action.",retry_focus:["State your action"]}})});const body=JSON.parse(result.body);assert.equal(result.statusCode,200);assert.equal(body.data.total_score,22);assert.equal(body.data.improved.length,1);assert.equal(body.data.still_missing.length,1);global.fetch=oldFetch;if(oldKey)process.env.DEEPSEEK_API_KEY=oldKey;else delete process.env.DEEPSEEK_API_KEY});
test("invalid provider JSON is converted to a friendly structured error",async()=>{const oldFetch=global.fetch,oldKey=process.env.DEEPSEEK_API_KEY;process.env.DEEPSEEK_API_KEY="test-placeholder-not-a-real-key";global.fetch=async()=>({ok:true,status:200,json:async()=>({choices:[{finish_reason:"stop",message:{content:"not json"}}]})});const result=await fn.main({httpMethod:"POST",headers:{"x-forwarded-for":"test-json"},body:JSON.stringify({action:"generate",...base})});const body=JSON.parse(result.body);assert.equal(result.statusCode,502);assert.equal(body.code,"INVALID_RESPONSE");global.fetch=oldFetch;if(oldKey)process.env.DEEPSEEK_API_KEY=oldKey;else delete process.env.DEEPSEEK_API_KEY});
