"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),vm=require("node:vm"),path=require("node:path");
const source=fs.readFileSync(path.join(__dirname,"../dist/mock-interview.js"),"utf8");
function storage(initial={}){const values=new Map(Object.entries(initial));return{getItem:key=>values.has(key)?values.get(key):null,setItem:(key,value)=>values.set(key,String(value)),removeItem:key=>values.delete(key),snapshot:()=>Object.fromEntries(values)}}
function load(localStorage=storage()){const window={EIT_CONFIG:{mockInterviewEndpoint:""},localStorage,confirm:()=>true};vm.runInNewContext(source,{window,AbortController,setTimeout,clearTimeout,fetch:async()=>{throw new Error("unused")},console});return{mock:window.MockInterview,localStorage}}
const questions=Array.from({length:5},(_,i)=>({id:`q${i+1}`,question:`Question ${i+1}?`,chinese:`问题 ${i+1}`,competency:"Role fit",jd_connection:"JD"}));
const feedback={relevance_score:5,structure_score:4,evidence_score:3,action_result_score:2,clarity_score:4,english_score:5,total_score:23,overall_diagnosis:"Clear and relevant.",strengths:["Role connection"],biggest_weakness:"Needs a result.",improvement_advice:["Add a result"],language_fixes:[],better_structure:["Point","Evidence","Action","Result","Tie-back"],suggested_answer:"Add your real result.",retry_focus:["Add a real result"],improved:["Clearer action"],still_missing:["Real metric"]};

test("mock persistence uses a separate versioned key and preserves learning data",()=>{const localStorage=storage({"interview-sprint-v2":JSON.stringify({sentinel:true})}),{mock}=load(localStorage);Object.assign(mock._session,{id:"one",createdAt:new Date().toISOString(),position:"Product Intern",jd:"Research users",questions,current:0,attempts:[[ {answer:"I researched users.",feedback}],[],[],[],[]],screen:"feedback",feedback});mock._persist();const all=localStorage.snapshot(),saved=JSON.parse(all[mock._storageKey]);assert.equal(mock._storageKey,"eit-mock-interview-v1");assert.equal(JSON.parse(all["interview-sprint-v2"]).sentinel,true);assert.equal(saved.version,1);assert.equal(saved.records[0].attempts[0][0].feedback.total_score,23)});

test("history keeps only the five most recent sessions",()=>{const {mock,localStorage}=load();for(let i=0;i<6;i++){Object.assign(mock._session,{id:`session-${i}`,createdAt:new Date(2026,0,i+1).toISOString(),position:`Role ${i}`,jd:"JD",questions,current:0,attempts:[[],[],[],[],[]],screen:"question"});mock._persist()}const saved=JSON.parse(localStorage.getItem(mock._storageKey));assert.equal(saved.records.length,5);assert.equal(saved.records[0].id,"session-5");assert.equal(saved.records.some(record=>record.id==="session-0"),false)});

test("damaged, old, and incomplete storage safely fall back",()=>{for(const raw of ["not json",JSON.stringify({version:0,records:[]}),JSON.stringify({version:1,activeId:"broken",records:[{id:"broken"}]})]){const localStorage=storage({"eit-mock-interview-v1":raw}),{mock}=load(localStorage),saved=mock._loadStore();assert.equal(saved.version,1);assert.equal(saved.records.length,0);assert.equal(mock.render().includes("Start Mock Interview"),true)}});

test("a stored retry and completed summary can be restored without an API call",()=>{const {mock,localStorage}=load(),attempts=Array.from({length:5},()=>[{answer:"First answer",feedback},{answer:"Better answer",feedback}]);Object.assign(mock._session,{id:"complete",createdAt:new Date().toISOString(),company:"Example",position:"Operations Intern",jd:"Analyze data",questions,current:4,attempts,screen:"summary"});mock._session.summary=mock._summaryData();mock._persist();const restored=load(localStorage).mock,record=restored._loadStore().records[0];assert.equal(restored._applyRecord(record),true);assert.equal(restored._session.attempts[0].length,2);assert.equal(restored._session.summary.latest.length,5);assert.equal(restored.render().includes("本轮模拟面试完成"),true)});

test("legacy English feedback remains readable with bilingual score labels",()=>{const {mock}=load(),attempts=[[{answer:"My original English answer.",feedback}],[],[],[],[]];Object.assign(mock._session,{questions,attempts,current:0,screen:"feedback",feedback});const html=mock.render();assert.match(html,/相关性 Relevance/);assert.match(html,/Needs a result/);assert.match(html,/My original English answer/);assert.match(html,/参考回答 Suggested Answer/)});

test("frontend maps timeout, balance, network, JSON, and rate errors to friendly messages",()=>{const {mock}=load();for(const code of ["TIMEOUT","INSUFFICIENT_BALANCE","NETWORK_ERROR","INVALID_RESPONSE","RATE_LIMITED","NOT_CONFIGURED"]){const message=mock._friendlyError({code});assert.equal(typeof message,"string");assert.ok(message.length>8);assert.doesNotMatch(message,/stack|DEEPSEEK_API_KEY|Bearer/)}});

test("summary uses the latest attempt for each of five questions",()=>{const {mock}=load();mock._session.attempts=Array.from({length:5},()=>[{feedback:{...feedback,relevance_score:1}},{feedback}]);const result=mock._summaryData();assert.equal(result.latest.length,5);assert.equal(result.avg.relevance_score,5);assert.equal(result.ranked[0],"relevance_score");assert.equal(result.ranked.at(-1),"action_result_score")});
