"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const enabled=process.env.EIT_REAL_API==="1",chromium=enabled?require("playwright").chromium:null,url="http://127.0.0.1:4173/",hasChinese=value=>/[\u3400-\u9fff]/.test(String(value||""));
const dimensions=["relevance_score","structure_score","evidence_score","action_result_score","clarity_score","english_score"];

test("real eit-test bilingual interview completes and persists",{skip:!enabled,timeout:300000},async()=>{
  const browser=await chromium.launch({headless:true,executablePath:"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"});
  try{
  const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[];
  page.on("pageerror",error=>errors.push(error.message));page.on("console",message=>{if(message.type()==="error")errors.push(message.text())});
  await page.goto(url,{waitUntil:"networkidle"});await page.evaluate(()=>{localStorage.removeItem("eit-mock-interview-v1");localStorage.setItem("interview-sprint-v2",JSON.stringify({version:2,items:{bilingual_real_test:{status:"known"}},questions:{},daily:{date:"2099-01-01",count:1},goal:10}))});await page.reload({waitUntil:"networkidle"});
  await page.click('[data-route="mock"]');await page.fill("#mockCompany","Example Company");await page.fill("#mockPosition","Product Operations Intern");await page.fill("#mockJd","Support user research, analyze campaign performance, communicate findings, coordinate stakeholders, solve operational problems, and execute content experiments.");await page.click('#mockSetup button[type="submit"]');await page.waitForSelector("text=Question 1 / 5",{timeout:45000});
  const questionData=await page.evaluate(()=>window.MockInterview._session.questions);assert.equal(questionData.length,5);assert.ok(questionData.every(q=>/[A-Za-z]/.test(q.question)&&hasChinese(q.chinese)));

  await page.fill("#mockAnswer","In a university project, I reviewed survey responses from students. I grouped recurring issues, shared the findings with four teammates, and we changed the onboarding guide. I did not measure the final outcome.");await page.click('#mockAnswerForm button[type="submit"]');await page.waitForSelector("text=最大问题 Biggest Weakness",{timeout:45000});
  let first=await page.evaluate(()=>window.MockInterview._session.feedback);dimensions.forEach(key=>assert.ok(Number.isInteger(first[key])&&first[key]>=0&&first[key]<=5));assert.ok(hasChinese(first.overall_diagnosis));assert.ok(first.strengths.every(hasChinese));assert.ok(hasChinese(first.biggest_weakness));assert.ok(first.improvement_advice.every(hasChinese));assert.ok(first.better_structure.every(item=>hasChinese(item)&&/Point|Evidence|Action|Result|Tie-back/.test(item)));assert.ok(/[A-Za-z]/.test(first.suggested_answer));assert.ok(hasChinese(first.suggested_answer_rationale));assert.ok(first.retry_focus.every(hasChinese));
  await page.reload({waitUntil:"networkidle"});await page.click('[data-route="mock"]');await page.locator('[data-resume-id]').first().click();await page.waitForSelector("text=最大问题 Biggest Weakness");

  await page.click("#mockRetry");await page.fill("#mockAnswer","In a university project, I personally categorized survey responses from students and identified three recurring onboarding issues. I presented the findings to four teammates, and we simplified the onboarding guide. After the change, eight of ten test users completed the first task without help. This experience prepared me to use evidence and coordinate action in a product operations role.");await page.click('#mockAnswerForm button[type="submit"]');await page.waitForSelector("text=本次进步 Improved",{timeout:45000});
  const retry=await page.evaluate(()=>window.MockInterview._session.feedback);assert.ok(retry.improved.length&&retry.improved.every(hasChinese));assert.ok(retry.still_missing.length&&retry.still_missing.every(hasChinese));

  const answers=["I would first clarify the user group and research goal. I would review existing feedback, interview users with consistent questions, group the recurring needs, and share the evidence with the team. I would then connect the findings to one practical product operations action.","In a student project, I coordinated four teammates by defining owners and deadlines. I tracked open issues, raised a delay early, and helped the team adjust the work. We delivered the final presentation on time, and I learned to make responsibilities visible.","When deadlines overlap, I compare user impact, urgency, and dependencies. I confirm priorities with the project owner, divide the work into clear checkpoints, and communicate risks early. This helps me protect the most important outcome without hiding trade-offs.","I am interested in this position because it combines user understanding, data analysis, and execution. My project experience has taught me to turn feedback into practical actions, and I want to strengthen that ability in a product operations role."];
  for(const answer of answers){await page.click("#mockNext");await page.fill("#mockAnswer",answer);await page.click('#mockAnswerForm button[type="submit"]');await page.waitForSelector("text=最大问题 Biggest Weakness",{timeout:45000})}
  await page.click("#mockNext");await page.waitForSelector("text=本轮模拟面试完成");await page.waitForSelector("text=下一步直接练这些");assert.ok(hasChinese(await page.locator("#view").innerText()));
  await page.reload({waitUntil:"networkidle"});await page.click('[data-route="mock"]');await page.locator('[data-resume-id]').first().click();await page.waitForSelector("text=本轮模拟面试完成");
  const saved=await page.evaluate(()=>({mock:JSON.parse(localStorage.getItem("eit-mock-interview-v1")),learning:JSON.parse(localStorage.getItem("interview-sprint-v2"))}));assert.equal(saved.mock.version,1);assert.equal(saved.mock.records[0].completed,true);assert.equal(saved.mock.records[0].attempts[0].length,2);assert.ok(saved.mock.records[0].summary);assert.equal(saved.learning.items.bilingual_real_test.status,"known");assert.deepEqual(errors,[]);
  }finally{await browser.close()}
});
